databases:
  - name : pos
    databaseName: pos
    user: pos
    plan: free

services:
  - type: web
    name: pos
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    #preDeployCommand: "bundle exec rails db:migrate"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pos
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync:false- key: WEB_CONCURRENCY
        value: 2  #sensible default